name: Netlib自动登录

on:
  schedule:
    - cron: '0 20 * * 6'  # 每周六 20:00 执行
  workflow_dispatch:  # 允许手动运行

jobs:
  auto_login_netlib:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright and browser
        run: npx playwright install --with-deps chromium

      - name: Run lognin script
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }} # 从 GitHub Secrets 中获取
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}      # 从 GitHub Secrets 中获取
          NETLIB_ACCOUNTS: ${{ secrets.NETLIB_ACCOUNTS }}  # 从 GitHub Secrets 中获取
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}  # 👈 必须加上这一行
        run: npm start
